### ISSUE TITLE
add method isCSSColor

### ISSUE THREAD

**Issue by joranmulderij** [alex-myznikov/from_css_color#2]
Could you add a method `isCSSColor` that checks if the input string is a valid css color?

**Comment by joranmulderij** [comment]
I created a pull request for it.

**Comment by alex-myznikov** [comment]
Hi, thank you for your contribution! I'm a bit busy right now so will probably check the PR this weekend...

**Comment by alex-myznikov** [comment]
I've examined your PR and can not accept it yet, because:

- No test coverage is provided
- Current implementation of `isCSSColor` method will return `true` for '#wrong color string', 'rgbanything' and etc...

I agree that this method would be useful for the package so if you could fix the issues mentioned - I will reexamine it again. Otherwise I'll get to it later in the next couple weeks and finish it by myself.

**Comment by joranmulderij** [comment]
Thank you for your nice feedback.

I created tests for the function, and changed the checking algorithm to regex.

**Comment by alex-myznikov** [comment]
Thank you, will take a look at weekend!

**Comment by alex-myznikov** [comment]
#3 has been accepted and will be released soon. Closing this for now.
